import mongoose from 'mongoose';


const ParticipantSchema = new mongoose.Schema({
    //using autogenerated id
    _id: { type: mongoose.Schema.Types.ObjectId, auto: true }, 
  });

  
export default mongoose.model("Participant", ParticipantSchema);
