const ParticipantSchema = new mongoose.Schema({
    //using autogenerated id
    _id: { type: mongoose.Schema.Types.ObjectId, auto: true }, 
    role: { type: String, enum: ["participant"], default: "participant" },
  });
  
  module.exports = mongoose.model("Participant", ParticipantSchema);
  